sudo: false

language: java

jdk:
  - oraclejdk8

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
    - $HOME/.local

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p $HOME/bin/idris-jvm $HOME/.local/bin
  - wget https://github.com/mmhelloworld/idris-jvm/releases/download/1.0-SNAPSHOT-20170520/idris-jvm-1.0-SNAPSHOT-20170520.zip
  - unzip -o idris-jvm-1.0-SNAPSHOT-20170520.zip -d $HOME/bin/idris-jvm
  - export PATH=$HOME/bin/idris-jvm/codegen/bin:$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --resolver lts-8.15 --no-terminal --skip-ghc-check setup
  - bin/travis_long stack --resolver lts-8.15 --no-terminal --skip-ghc-check install idris

script:
  - mvn -pl :idris-jvm-integration-test test -B